version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: storypath-db
    environment:
      POSTGRES_USER: storypath
      POSTGRES_PASSWORD: storypath
      POSTGRES_DB: storypath
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: storypath-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"

volumes:
  db_data:
