name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Ensure pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
      - name: Fallback install pnpm globally
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then npm i -g pnpm@9; fi
      - name: Install dependencies (workspace)
        env:
          HUSKY: '0'
        run: pnpm install --no-frozen-lockfile --ignore-scripts
      - name: Validate sample story
        run: node tools/validate-story.mjs schemas/sample-story.json
      - name: Typecheck gateway
        working-directory: backend/gateway
        run: pnpm exec tsc -p tsconfig.json --noEmit
      - name: Typecheck content service
        working-directory: backend/services/content
        run: pnpm exec tsc -p tsconfig.json --noEmit
      - name: Typecheck progress service
        working-directory: backend/services/progress
        run: pnpm exec tsc -p tsconfig.json --noEmit

  smoke:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: storypath
          POSTGRES_PASSWORD: storypath
          POSTGRES_DB: storypath
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U storypath -d storypath"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Ensure pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
      - name: Fallback install pnpm globally
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then npm i -g pnpm@9; fi
      - name: Install all workspaces
        env:
          HUSKY: '0'
        run: pnpm install --no-frozen-lockfile --ignore-scripts
      - name: Generate Prisma client
        working-directory: backend
        run: pnpm exec prisma generate
      - name: Apply migrations and seed
        working-directory: backend
        env:
          DATABASE_URL: postgresql://storypath:storypath@127.0.0.1:5432/storypath
        run: |
          pnpm exec prisma migrate deploy
          pnpm run prisma:seed
      - name: Start content service
        env:
          PORT: 4001
        run: |
          nohup pnpm --filter content start &
      - name: Start progress service
        env:
          PORT: 4002
          DATABASE_URL: postgresql://storypath:storypath@127.0.0.1:5432/storypath
        run: |
          nohup pnpm --filter progress start &
      - name: Wait for services
        run: |
          for i in {1..30}; do
            curl -fsS http://127.0.0.1:4001/health && curl -fsS http://127.0.0.1:4002/health && break || true
            echo waiting...; sleep 2
          done
      - name: Run smoke test
        env:
          CONTENT_URL: http://127.0.0.1:4001
          PROGRESS_URL: http://127.0.0.1:4002
  run: pnpm dlx tsx tools/smoke.e2e.ts
